Use uMTPrd instead of f_gser for the default gadget
nisargjhaveri/AAWirelessDongle pull request #3
Opened 2023-10-07 21:49 UTC by BluemediaGER

This pull request replaces the gser function of the default gadget with a full MTP implementation ([uMTPrd](https://github.com/viveris/uMTP-Responder)). Some head units expect an MTP device and may not work correctly if the connected USB device does not behave like one.

2023-10-08 17:07 UTC, nisargjhaveri reviewed
Thanks for this! The change looks good logically, though I'd like to give it a try once to understand a couple of things better. I'll try to find some time soon.

2023-10-08 17:07 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/kernel.config
> +USB_FUNCTIONFS=y
Is this really required? `CONFIG_USB_CONFIGFS_F_FS` is already enabled and that should take care of this, no?

Also, even if this is required, doesn't it need to be `CONFIG_USB_FUNCTIONFS`?

2023-10-22 12:00 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/init.d/S92usb_gadget
> +	# Mount FunctionFS and start uMTPrd
`mount` needs to be done after we setup the function above. We can split this into three different init scripts, but that can be a different refactor. Never mind.

2023-10-22 12:01 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/umtprd/umtprd.conf
> +usb_product_id 0x0105
These doesn't seem to have any effect as such. But we can keep these for now until there is more clarity.

2023-10-22 12:02 UTC, nisargjhaveri commented on aa_wireless_dongle/board/common/kernel.config
> +USB_FUNCTIONFS=y
Please remove this?

2023-10-22 12:04 UTC, nisargjhaveri requested changes
I was able to play around with this and this looks good. Thanks! :)

2023-10-23 16:17 UTC, BluemediaGER commented on aa_wireless_dongle/board/common/rootfs_overlay/etc/umtprd/umtprd.conf
> +usb_product_id 0x0105
My guess is that these options are only used for GadgetFS mode. Unfortunately uMTPrd will not start without them.

2023-10-23 16:17 UTC, BluemediaGER commented on aa_wireless_dongle/board/common/kernel.config
> +USB_FUNCTIONFS=y
You're right. Removed it.

2023-10-23 16:19 UTC, BluemediaGER commented
Sorry for the delay, I've been quite busy with other stuff. I've made the necessary changes.

2023-10-23 17:04 UTC, nisargjhaveri approved these changes

2023-10-23 17:05 UTC, merged